### ISSUE TITLE
alarm-clock eats 100% of one CPU when idling

### ISSUE THREAD

**Issue by erlanger** [shaggytwodope/alarm-clock#1]
At some point alarm-clock uses 100% of the CPU when idling. I think some of the usleep(...) calls are not working properly, or maybe they are not being called at the proper place.

Thanks!!

**Comment by erlanger** [comment]
Did a litlle inspection, by running it in gdb, hitting ^C and seeing in what function it stops:

```
update_alarm_thread(gboolean thread)
```

Full stack trace for that thread:
```
Thread 7 (Thread 0x7fffe5da4700 (LWP 5708)):                                                                 [54/46312]
#0  0x00007ffff4ad4e55 in _xstat () at /usr/lib/libc.so.6
#1  0x00007ffff4aa3b3e in __tzfile_read () at /usr/lib/libc.so.6
#2  0x00007ffff4aa35c5 in tzset_internal () at /usr/lib/libc.so.6
#3  0x00007ffff4aa38ed in __tz_convert () at /usr/lib/libc.so.6
#4  0x0000555555567b17 in convert_back (convert=0x7ffff4d97460 <_tmbuf>) at alarm_thread.c:132
#5  0x0000555555568040 in get_iso_date_from_scheduled (alarm_name=0x7fffcc038d10 "alarm_1485194603")
    at alarm_thread.c:234
#6  0x000055555556852b in update_alarm_thread (thread=1) at alarm_thread.c:351
#7  0x0000555555568c41 in alarm_thread () at alarm_thread.c:557
#8  0x00007ffff552c175 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff4d9f454 in start_thread () at /usr/lib/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff4ae27df in clone () at /usr/lib/libc.so.6
```


I tried it several times and each time it stops at the `update_alarm_thread(...)` function, whereas I would expect it to stop at one of the `g_usleep(...)` function calls.

**Comment by shaggytwodope** [comment]
How long of a runtime before you see the high cpu usage? I might include the simple fix for time being, you are more then welcome to open a PR.
